disabled_rules:
  # force casting is a common part of UIKit development discretion is left to the developer
  - force_cast

opt_in_rules:
  - indentation_width

trailing_comma:
  # Providing trailing commas on multi-line collection literals produces cleaner diffs
  mandatory_comma: true

indentation_width:
  indentation_width: 2

identifier_name:
  min_length: 1
