name: Build and Test

env:
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    env:
      afterpay-scheme: Afterpay
      example-scheme: Example
      destination: platform=iOS Simulator,name=iPhone 11,OS=13.5
      workspace: Afterpay.xcworkspace

    steps:
    - uses: actions/checkout@v2

    - name: Cache Mint Packages
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Install Dependencies
      run: Tools/mint/mint bootstrap

    - name: SwiftLint
      run Tools/mint/mint run swiftlint --reporter github-actions-logging

    - name: Build SDK Project
      run: |
        xcodebuild build-for-testing \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.afterpay-scheme }} \
          -destination '${{ env.destination }}'
  
    - name: Test SDK Project
      run: |
        xcodebuild test-without-building \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.afterpay-scheme }} \
          -destination '${{ env.destination }}'

    - name: Build Example Project
      run: |
        xcodebuild \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.example-scheme }} \
          -destination '${{ env.destination }}'
